name: Images
on:
  workflow_call:
  push:
    branches:
      - "development"
      - "wip/new-release"
  pull_request:
    branches: [ "**" ]

jobs:
  depend-on-kernels:
    name: (Kernel builds)
    uses: ./.github/workflows/kernels.yml
  depend-on-overlay:
    name: (Overlay builds)
    uses: ./.github/workflows/overlay.yml
  Matrix:
    runs-on: [ubuntu-24.04]
    outputs:
      matrix: ${{ steps.build-matrix.outputs.matrix }}
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - uses: "cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72"
        with:
          nix_path:
      - id: build-matrix
        name: "Generate Build Matrix"
        env:
          BUCKET: images
        run: |
          PS4=" $ "
          set -xeu
          (
          printf "matrix=%s\n" "$(nix-instantiate --show-trace --argstr bucket "$BUCKET" --strict --eval --json ./.ci/build-matrices.nix)"
          ) >> "$GITHUB_OUTPUT"
  Builds:
    name: ${{ matrix.name }}
    needs:
      - depend-on-kernels
      - depend-on-overlay
      - Matrix
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false # Try to build everything
      matrix: ${{ fromJSON(needs.Matrix.outputs.matrix) }}
    steps:
      - uses: "actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683"
      - uses: "cachix/install-nix-action@08dcb3a5e62fa31e2da3d490afc4176ef55ecd72"
        with:
          nix_path:
      - run: nix-build ./release.nix --system "${{ matrix.system }}" --attr '${{ matrix.attr }}'
